"""Tests for the train_replay CLI."""

from __future__ import annotations

import pickle
from pathlib import Path

from click.testing import CliRunner

from train_replay.cli.main import cli


def _write_sample_trace(path: Path) -> None:
    """Write a minimal Flight Recorder pickle file for testing."""
    data = {
        "entries": [
            {
                "rank": 0,
                "pg_name": "default",
                "collective_seq": "all_reduce",
                "p2p_src": None,
                "p2p_dst": None,
                "input_sizes": [[4096]],
                "time_created_ns": 1000,
                "time_started_ns": 1100,
                "time_finished_ns": 1200,
                "frames": [],
                "seq_id": 1,
            },
            {
                "rank": 1,
                "pg_name": "default",
                "collective_seq": "all_reduce",
                "p2p_src": None,
                "p2p_dst": None,
                "input_sizes": [[4096]],
                "time_created_ns": 1000,
                "time_started_ns": 1100,
                "time_finished_ns": 1200,
                "frames": [],
                "seq_id": 1,
            },
            {
                "rank": 0,
                "pg_name": "default",
                "collective_seq": "all_reduce",
                "p2p_src": None,
                "p2p_dst": None,
                "input_sizes": [[8192]],
                "time_created_ns": 2000,
                "time_started_ns": 2100,
                "time_finished_ns": 2200,
                "frames": [],
                "seq_id": 2,
            },
            {
                "rank": 1,
                "pg_name": "default",
                "collective_seq": "all_reduce",
                "p2p_src": None,
                "p2p_dst": None,
                "input_sizes": [[8192]],
                "time_created_ns": 2000,
                "time_started_ns": 2100,
                "time_finished_ns": 2200,
                "frames": [],
                "seq_id": 2,
            },
        ]
    }
    with open(path, "wb") as f:
        pickle.dump(data, f)


def test_ingest_command(tmp_path: Path) -> None:
    """ingest command prints graph node count."""
    trace_path = tmp_path / "trace.pkl"
    _write_sample_trace(trace_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["ingest", str(trace_path)])
    assert result.exit_code == 0
    assert "Loaded" in result.output
    assert "Built causal graph" in result.output


def test_trace_command(tmp_path: Path) -> None:
    """trace command prints causal ancestors."""
    trace_path = tmp_path / "trace.pkl"
    _write_sample_trace(trace_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["trace", "tensor:0:1:out", str(trace_path)])
    assert result.exit_code == 0
    assert "Causal ancestors" in result.output
    assert "act:0:all_reduce:1" in result.output


def test_record_command(tmp_path: Path) -> None:
    """record command prints action count and digest."""
    trace_path = tmp_path / "trace.pkl"
    _write_sample_trace(trace_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["record", str(trace_path)])
    assert result.exit_code == 0
    assert "Recorded" in result.output
    assert "Bundle digest" in result.output


def test_replay_command(tmp_path: Path) -> None:
    """replay command prints replay result with causal ancestors."""
    trace_path = tmp_path / "trace.pkl"
    _write_sample_trace(trace_path)
    runner = CliRunner()
    result = runner.invoke(
        cli,
        [
            "replay",
            str(trace_path),
            "tensor:0:2:out",
            "--rank", "0",
            "--run-id", "test-run",
            "--epoch", "1",
        ],
    )
    assert result.exit_code == 0, f"Exit code {result.exit_code}: {result.output}"
    assert "Replay Result" in result.output
    assert "Causal ancestors" in result.output
    assert "Suspicious actions" in result.output
    # tensor:0:2:out was generated by act:0:all_reduce:2
    assert "act:0:all_reduce:2" in result.output


def test_replay_command_default_rank(tmp_path: Path) -> None:
    """replay command uses default rank 0."""
    trace_path = tmp_path / "trace.pkl"
    _write_sample_trace(trace_path)
    runner = CliRunner()
    result = runner.invoke(cli, ["replay", str(trace_path), "tensor:0:1:out"])
    assert result.exit_code == 0, f"Exit code {result.exit_code}: {result.output}"
    assert "Replay Result" in result.output
    assert "rank 0" in result.output


def test_replay_command_missing_entity(tmp_path: Path) -> None:
    """replay command handles entity with no ancestors."""
    trace_path = tmp_path / "trace.pkl"
    _write_sample_trace(trace_path)
    runner = CliRunner()
    # "tensor:99:99:out" does not exist in the graph
    result = runner.invoke(cli, ["replay", str(trace_path), "tensor:99:99:out"])
    # Should exit cleanly with empty ancestors list
    assert result.exit_code == 0, f"Exit code {result.exit_code}: {result.output}"
    assert "Replay Result" in result.output


def test_replay_with_suspicious_actions(tmp_path: Path) -> None:
    """replay command shows suspicious (FULL mode) actions."""
    trace_path = tmp_path / "trace.pkl"
    _write_sample_trace(trace_path)
    runner = CliRunner()
    # Add a risk override by using --rank; the all_reduce collective triggers MUTATE_EXTERNAL
    # which results in FULL recording mode per compile_recording_policy
    result = runner.invoke(
        cli,
        [
            "replay",
            str(trace_path),
            "tensor:0:1:out",
            "--rank", "0",
        ],
    )
    assert result.exit_code == 0, f"Exit code {result.exit_code}: {result.output}"
    assert "Suspicious actions" in result.output


# ---------------------------------------------------------------------------
# admin safe-mode subcommand tests
# ---------------------------------------------------------------------------


def test_admin_safe_mode_status_default_off() -> None:
    """admin safe-mode --status reports OFF by default."""
    from train_replay.cli.safemode import global_safe_mode

    global_safe_mode.clear()
    runner = CliRunner()
    result = runner.invoke(cli, ["admin", "safe-mode", "--status"])
    assert result.exit_code == 0, f"Exit {result.exit_code}: {result.output}"
    assert "OFF" in result.output


def test_admin_safe_mode_on() -> None:
    """admin safe-mode --on activates safe mode."""
    from train_replay.cli.safemode import global_safe_mode

    global_safe_mode.clear()
    runner = CliRunner()
    result = runner.invoke(cli, ["admin", "safe-mode", "--on"])
    assert result.exit_code == 0, f"Exit {result.exit_code}: {result.output}"
    assert "activated" in result.output.lower()
    assert global_safe_mode.status() is True


def test_admin_safe_mode_off() -> None:
    """admin safe-mode --off deactivates safe mode."""
    from train_replay.cli.safemode import global_safe_mode

    global_safe_mode.trigger()
    runner = CliRunner()
    result = runner.invoke(cli, ["admin", "safe-mode", "--off"])
    assert result.exit_code == 0, f"Exit {result.exit_code}: {result.output}"
    assert "deactivated" in result.output.lower()
    assert global_safe_mode.status() is False


def test_admin_safe_mode_mutually_exclusive() -> None:
    """admin safe-mode --on --off aborts with error."""
    from train_replay.cli.safemode import global_safe_mode

    global_safe_mode.clear()
    runner = CliRunner()
    result = runner.invoke(cli, ["admin", "safe-mode", "--on", "--off"])
    assert result.exit_code != 0
    assert "mutually exclusive" in result.output.lower()


def test_admin_safe_mode_no_flags_shows_status() -> None:
    """admin safe-mode with no flags defaults to showing status."""
    from train_replay.cli.safemode import global_safe_mode

    global_safe_mode.clear()
    runner = CliRunner()
    result = runner.invoke(cli, ["admin", "safe-mode"])
    assert result.exit_code == 0, f"Exit {result.exit_code}: {result.output}"
    assert "OFF" in result.output


def test_admin_safe_mode_status_when_active() -> None:
    """admin safe-mode --status reports ON when active."""
    from train_replay.cli.safemode import global_safe_mode

    global_safe_mode.trigger()
    runner = CliRunner()
    result = runner.invoke(cli, ["admin", "safe-mode", "--status"])
    assert result.exit_code == 0, f"Exit {result.exit_code}: {result.output}"
    assert "ON" in result.output


# ---------------------------------------------------------------------------
# resume command tests
# ---------------------------------------------------------------------------


def test_resume_clears_safe_mode() -> None:
    """resume command clears safe mode."""
    from train_replay.cli.safemode import global_safe_mode

    global_safe_mode.trigger()
    assert global_safe_mode.status() is True
    runner = CliRunner()
    result = runner.invoke(cli, ["resume"])
    assert result.exit_code == 0, f"Exit {result.exit_code}: {result.output}"
    assert "Safe mode cleared" in result.output
    assert global_safe_mode.status() is False


def test_resume_when_not_in_safe_mode() -> None:
    """resume is a no-op when safe mode is already off."""
    from train_replay.cli.safemode import global_safe_mode

    global_safe_mode.clear()
    runner = CliRunner()
    result = runner.invoke(cli, ["resume"])
    assert result.exit_code == 0, f"Exit {result.exit_code}: {result.output}"
    assert "Safe mode cleared" in result.output
